name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: vet & fmt
        run: make fmt
      - name: Test
        run: make test
      - name: Static check
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
